apiVersion: v1
kind: Pod
metadata:
  name: registry-externo
  namespace: novo-teste
  labels:
    app: registry-externo
    team: teste
    env: lab
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:1.27.5
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false