apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  namespace: tipsbank-contas
type: Opaque
stringData:
  POSTGRES_DB: tipsbank
  POSTGRES_USER: tipsbank
  POSTGRES_PASSWORD: TipsBank123
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  namespace: tipsbank-transacoes
type: Opaque
stringData:
  POSTGRES_DB: tipsbank
  POSTGRES_USER: tipsbank
  POSTGRES_PASSWORD: TipsBank123
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  namespace: tipsbank-auditoria
type: Opaque
stringData:
  POSTGRES_DB: tipsbank
  POSTGRES_USER: tipsbank
  POSTGRES_PASSWORD: TipsBank123
