apiVersion: v1
kind: Pod
metadata:
  name: debug-api-contas
  namespace: tipsbank-contas
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: registry-secret
  containers:
    - name: api-contas
      image: ghcr.io/brunosantostecinf-shell/tipsbank-api-contas:v1.0.0
      command: ["sh", "-c", "sleep 3600"]
      envFrom:
        - configMapRef:
            name: configmap-app
        - secretRef:
            name: secret-db
