apiVersion: v1
kind: Pod
metadata:
  name: teste-psql
  namespace: tipsbank-contas
  labels:
    app: teste-psql
spec:
  restartPolicy: Never
  containers:
    - name: teste
      image: postgres:16-alpine
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap-app
              key: POSTGRES_HOST

        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-app
              key: POSTGRES_PORT

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: POSTGRES_DB

---
apiVersion: v1
kind: Pod
metadata:
  name: teste-psql
  namespace: tipsbank-transacoes
  labels:
    app: teste-psql
spec:
  restartPolicy: Never
  containers:
    - name: teste
      image: postgres:16-alpine
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap-app
              key: POSTGRES_HOST

        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-app
              key: POSTGRES_PORT

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: POSTGRES_DB

---
apiVersion: v1
kind: Pod
metadata:
  name: teste-psql
  namespace: tipsbank-auditoria
  labels:
    app: teste-psql
spec:
  restartPolicy: Never
  containers:
    - name: teste
      image: postgres:16-alpine
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap-app
              key: POSTGRES_HOST

        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-app
              key: POSTGRES_PORT

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: POSTGRES_DB
