apiVersion: v1
kind: ConfigMap
metadata:
  name: transacoes-config
  namespace: tipsbank-transacoes
data:
  CONTAS_URL: "http://api-contas.tipsbank-contas.svc.cluster.local:8080"
  AUDITORIA_URL: "http://auditoria.tipsbank-auditoria.svc.cluster.local:8080"
  POSTGRES_HOST: "postgres.tipsbank-contas.svc.cluster.local"
