apiVersion: v1
kind: Secret
metadata:
  name: transacoes-secret
  namespace: tipsbank-transacoes
type: Opaque
stringData:
  DB_URL: "postgresql+psycopg://tipsbank:TipsBank123@postgres.tipsbank-contas.svc.cluster.local:5432/tipsbank"
