apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auditoria
  namespace: tipsbank-monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: auditoria

  namespaceSelector:
    matchNames:
      - tipsbank-auditoria

  endpoints:
    - port: http
      path: /metrics
      interval: 15s